# Makefile for Win32
TOP  = ../..
!include "$(TOP)/win32.mak"


SRCS = agv_example.c fractals.c gears.c hanoi.c lineblend.c moth.c noof.c rings.c steam.c text3d.c worms.c

!include "$(TOP)/glutwin32.mak"

# dependencies
agv_example.exe	: agviewer.obj
fractals.exe	: fracviewer.obj
