# Makefile for Win32

TOP  = ../../..

!include "$(TOP)/win32.mak"
SRCS = glflare.c

!include "$(TOP)/glutwin32.mak"

# dependencies
glflare.exe	: loadlum.obj
glflare.obj	: glflare.c vec3d.c loadlum.h
