# Makefile for Win32
TOP  = ../../..
!include "$(TOP)/win32.mak"
SRCS = sixviews.c cview2smap.c st2rvec.c smapmesh.c

!include "$(TOP)/glutwin32.mak"

# dependencies
cview2smap.exe: drawmesh.obj makemesh.obj
