# Makefile for Win32
TOP  = ../..
!include "$(TOP)/win32.mak"


SRCS = mui_test.c multi_test.c

EXTRALIBS = $(MUI)
DEPLIBS = $(MUI)

!include "$(TOP)/glutwin32.mak"

test : mui_test.exe multi_test.exe
