# Makefile for Win32

TOP  = ../../..

!include "$(TOP)/win32.mak"
SRCS = atlantis.c

!include "$(TOP)/glutwin32.mak"

# dependencies
atlantis.exe	: dolphin.obj shark.obj swim.obj whale.obj
atlantis.obj	: atlantis.h
