# Makefile for Win32

TOP  = ../..
!include "$(TOP)/win32.mak"
SRCS = showtxf.c txfdemo.c simpletxf.c

!include "$(TOP)/glutwin32.mak"

# dependencies
txfdemo.exe	\
simpletxf.exe	\
showtxf.exe	: texfont.obj
