# Makefile for Win32

TOP  = ../../..

!include "$(TOP)/win32.mak"
SRCS = Editor.c

!include "$(TOP)/glutwin32.mak"
CFLAGS = $(CFLAGS) -DYACME_DBG

# dependencies
Editor.exe	: invertmat.obj
Editor.c	: mallocbis.h RGBA.h
